name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Push a GitLab
        env:
          GITLAB_REPO: git@git.ovan.de:ovan.de/typo3-headless.git
          GITLAB_BRANCH: extension/graphql3
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan git.ovan.de >> ~/.ssh/known_hosts
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "sync@github.actions"
          git remote add gitlab "$GITLAB_REPO"
          git push gitlab HEAD:$GITLAB_BRANCH --force
